[package]
name = "generics_10"
version = "0.1.0"
authors = ["sinewyk <sinewyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
